[phases.build]
  cmds = [
    "npm install --production --no-cache",
    "npm rebuild sqlite3"
  ]

[phases.start]
  cmd = "npm start"

[variables]
  NODE_ENV = "production"
  NPM_CONFIG_CACHE = "/tmp/.npm" 