[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "never"

[variables]
  NODE_ENV = "production"
  NPM_CONFIG_CACHE = "/tmp/.npm"
  NPM_CONFIG_LOGLEVEL = "warn" 